services:
  - type: web
    name: smartgrade-vision-vault
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: USE_CLOUD_STORAGE
        value: "True"
      - key: GCS_BUCKET_NAME
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
